# Generated by Django 5.1.13 on 2025-10-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished_date',
            new_name='published_date',
        ),
    ]
